-- ====================================================================
-- SYSTEM: RAILWAY RESERVATION SYSTEM (RRS)
-- TARGET DATABASE ENGINE: Oracle SQL*Plus / Docker Oracle Database XE
-- SCHEMATIC VERSION: 3.0 (Enterprise Refinement Master)
-- ====================================================================

-- STEP 1: DROP TABLES IN CORRECT SEQUENCE (Prevents Foreign Key Conflicts)
DROP VIEW v_booking_fare_estimates;
DROP TABLE master_passengers CASCADE CONSTRAINTS;
DROP TABLE payments CASCADE CONSTRAINTS;
DROP TABLE tickets CASCADE CONSTRAINTS;
DROP TABLE bookings CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE train_composition CASCADE CONSTRAINTS;
DROP TABLE coach_classes CASCADE CONSTRAINTS;
DROP TABLE train_instances CASCADE CONSTRAINTS;
DROP TABLE routes CASCADE CONSTRAINTS;
DROP TABLE trains CASCADE CONSTRAINTS;
DROP TABLE stations CASCADE CONSTRAINTS;

-- STEP 2: CREATE CORE INFRASTRUCTURE TABLES

CREATE TABLE stations (
    stn_code VARCHAR2(10) PRIMARY KEY,
    city VARCHAR2(100) NOT NULL,
    stn_name VARCHAR2(255) NOT NULL,
    state VARCHAR2(100) NOT NULL,
    CONSTRAINT chk_stn_code_upper CHECK (stn_code = UPPER(stn_code))
);

CREATE TABLE trains (
    train_no VARCHAR2(10) PRIMARY KEY,
    train_name VARCHAR2(255) NOT NULL,
    train_type VARCHAR2(50) NOT NULL,
    active_days CHAR(7) DEFAULT '1111111' NOT NULL, -- Binary schedule string (MTWTFSS)
    CONSTRAINT chk_train_no_numeric CHECK (REGEXP_LIKE(train_no, '^[0-9]+$')),
    CONSTRAINT chk_train_type CHECK (train_type IN ('Express', 'Superfast', 'Rajdhani', 'Shatabdi', 'Passenger', 'Duronto'))
);

-- Refinement 3: Time Tracking optimized to absolute numerical offsets from midnight (0 to 1439 minutes)
-- This eliminates sorting issues and simplifies multi-day scheduling computations.
CREATE TABLE routes (
    route_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_no VARCHAR2(10) NOT NULL REFERENCES trains(train_no) ON DELETE CASCADE,
    stn_code VARCHAR2(10) NOT NULL REFERENCES stations(stn_code),
    arrival_time NUMBER(4),  -- Minutes since midnight (e.g. 08:05 is 485)
    depart_time NUMBER(4),   -- Minutes since midnight (e.g. 16:50 is 1010)
    sequence_num NUMBER(3) NOT NULL,
    distance_from_source NUMBER(5) DEFAULT 0 NOT NULL,
    CONSTRAINT chk_seq_num CHECK (sequence_num > 0),
    CONSTRAINT chk_distance CHECK (distance_from_source >= 0),
    CONSTRAINT chk_arr_time CHECK (arrival_time IS NULL OR (arrival_time BETWEEN 0 AND 1439)),
    CONSTRAINT chk_dep_time CHECK (depart_time IS NULL OR (depart_time BETWEEN 0 AND 1439)),
    CONSTRAINT uq_train_stn UNIQUE (train_no, stn_code),
    CONSTRAINT uq_train_seq UNIQUE (train_no, sequence_num)
);

CREATE TABLE train_instances (
    train_no VARCHAR2(10) NOT NULL REFERENCES trains(train_no),
    run_date DATE NOT NULL,
    actual_departure TIMESTAMP,
    actual_arrival TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'Scheduled' NOT NULL,
    delay_minutes NUMBER(4) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_train_instances PRIMARY KEY (train_no, run_date),
    CONSTRAINT chk_instance_status CHECK (status IN ('Scheduled', 'Running', 'Delayed', 'Cancelled', 'Completed'))
);

-- Refinement 1A: Coach Classes Master Catalog defining static configurations
CREATE TABLE coach_classes (
    class_code VARCHAR2(10) PRIMARY KEY, -- E.g., '1A', '2A', '3A', 'SL', 'CC', '2S'
    class_name VARCHAR2(100) NOT NULL,    -- E.g., 'AC First Class', 'AC 3-Tier', 'Sleeper Class'
    total_seats NUMBER(3) NOT NULL,       -- Total operational capacity per coach
    base_fare_multiplier NUMBER(4, 2) NOT NULL, -- Fare factor applied per kilometer (e.g., 2.45)
    CONSTRAINT chk_total_seats CHECK (total_seats > 0),
    CONSTRAINT chk_multiplier CHECK (base_fare_multiplier > 0.00)
);

-- Refinement 1B: Train Composition Table (Junction linking dynamic run configurations)
-- Provides flexibility to add/remove specific coaches on any given scheduled operational date.
CREATE TABLE train_composition (
    composition_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_no VARCHAR2(10) NOT NULL,
    run_date DATE NOT NULL,
    coach_label VARCHAR2(10) NOT NULL, -- E.g., 'B1', 'B2', 'H1'
    class_code VARCHAR2(10) NOT NULL REFERENCES coach_classes(class_code),
    CONSTRAINT fk_comp_train_instance FOREIGN KEY (train_no, run_date) REFERENCES train_instances(train_no, run_date) ON DELETE CASCADE,
    CONSTRAINT uq_train_run_coach UNIQUE (train_no, run_date, coach_label)
);

-- STEP 3: USER & TRANSACTION INFRASTRUCTURE

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    mobile VARCHAR2(15) UNIQUE NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    dob DATE NOT NULL,
    gender VARCHAR2(10) NOT NULL,
    -- Refinement 3: Restricting password_hash to exact length of standard bcrypt format (60 chars)
    password_hash CHAR(60) NOT NULL,
    role VARCHAR2(20) DEFAULT 'Passenger' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_user_email CHECK (email LIKE '%@%.%'),
    CONSTRAINT chk_user_mobile CHECK (REGEXP_LIKE(mobile, '^[0-9]{10}$')),
    CONSTRAINT chk_user_gender CHECK (gender IN ('Male', 'Female', 'Other')),
    CONSTRAINT chk_user_role CHECK (role IN ('Admin', 'Station Master', 'Passenger', 'TC'))
);

-- Refinement 2: Dynamic Stop-Specific Fare Columns added (source_stn_code, destination_stn_code)
CREATE TABLE bookings (
    pnr_10 VARCHAR2(10) PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(user_id),
    train_no VARCHAR2(10) NOT NULL,
    journey_date DATE NOT NULL,
    source_stn_code VARCHAR2(10) NOT NULL REFERENCES stations(stn_code),
    destination_stn_code VARCHAR2(10) NOT NULL REFERENCES stations(stn_code),
    quota VARCHAR2(5) DEFAULT 'GN' NOT NULL, 
    total_fare NUMBER(10, 2) NOT NULL,
    booking_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'Booked' NOT NULL,
    CONSTRAINT fk_booking_train_instance FOREIGN KEY (train_no, journey_date) REFERENCES train_instances(train_no, run_date),
    CONSTRAINT chk_pnr_format CHECK (REGEXP_LIKE(pnr_10, '^[0-9]{10}$')),
    CONSTRAINT chk_booking_fare CHECK (total_fare >= 0),
    CONSTRAINT chk_booking_status CHECK (status IN ('Booked', 'Cancelled', 'Partially_Cancelled')),
    CONSTRAINT chk_quota CHECK (quota IN ('GN', 'TQ', 'LD', 'DF', 'SR')),
    CONSTRAINT chk_different_stns CHECK (source_stn_code <> destination_stn_code)
);

CREATE TABLE tickets (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnr_10 VARCHAR2(10) NOT NULL REFERENCES bookings(pnr_10) ON DELETE CASCADE,
    passenger_name VARCHAR2(150) NOT NULL,
    passenger_age NUMBER(3) NOT NULL,
    passenger_gender VARCHAR2(10) NOT NULL,
    -- Tickets reference the dynamic composition layout rather than a static catalog row
    composition_id NUMBER REFERENCES train_composition(composition_id),
    seat_num NUMBER(3),
    allocated_berth VARCHAR2(5), 
    -- Refinement 3: Strict Status constraint checks to avoid dirty entries
    status VARCHAR2(5) NOT NULL, 
    wl_number NUMBER(3) DEFAULT 0,
    CONSTRAINT chk_pass_age CHECK (passenger_age BETWEEN 0 AND 125),
    CONSTRAINT chk_pass_gender CHECK (passenger_gender IN ('Male', 'Female', 'Other')),
    CONSTRAINT chk_ticket_status CHECK (status IN ('CNF', 'RAC', 'WL', 'CAN')),
    CONSTRAINT chk_berth_type CHECK (allocated_berth IS NULL OR allocated_berth IN ('LB', 'MB', 'UB', 'SL', 'SU', 'WS'))
);

CREATE TABLE payments (
    trans_id VARCHAR2(100) PRIMARY KEY,
    pnr_10 VARCHAR2(10) NOT NULL REFERENCES bookings(pnr_10),
    amount NUMBER(10, 2) NOT NULL,
    payment_status VARCHAR2(20) DEFAULT 'Success' NOT NULL,
    payment_method VARCHAR2(50) NOT NULL,
    paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_pay_amount CHECK (amount >= 0),
    CONSTRAINT chk_pay_status CHECK (payment_status IN ('Success', 'Failed', 'Refunded', 'Pending')),
    CONSTRAINT chk_pay_method CHECK (payment_method IN ('UPI', 'Credit Card', 'Debit Card', 'Net Banking', 'Wallet'))
);

CREATE TABLE master_passengers (
    mstr_pass_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    name VARCHAR2(150) NOT NULL,
    age NUMBER(3) NOT NULL,
    gender VARCHAR2(10) NOT NULL,
    preferred_berth VARCHAR2(5),
    CONSTRAINT chk_mstr_age CHECK (age BETWEEN 0 AND 125),
    CONSTRAINT chk_mstr_gender CHECK (gender IN ('Male', 'Female', 'Other')),
    CONSTRAINT chk_mstr_berth CHECK (preferred_berth IS NULL OR preferred_berth IN ('LB', 'MB', 'UB', 'SL', 'SU', 'WS'))
);

-- STEP 4: INDEX OPTIMIZATION (Speeding up Lookup Paths)
CREATE INDEX idx_routes_lookup ON routes(stn_code, train_no);
CREATE INDEX idx_bookings_journey ON bookings(journey_date, train_no);
CREATE INDEX idx_tickets_pnr ON tickets(pnr_10);
CREATE INDEX idx_comp_train ON train_composition(train_no, run_date);
CREATE INDEX idx_mstr_pass_user ON master_passengers(user_id);

-- STEP 5: CREATING SCHEMATIC VIEWS FOR APPLICATION INTERFACES
-- Refinement 2 View: Calculates distance dynamically and checks against structural fares.
CREATE OR REPLACE VIEW v_booking_fare_estimates AS
SELECT 
    b.pnr_10,
    b.train_no,
    b.source_stn_code,
    b.destination_stn_code,
    r_src.distance_from_source AS src_km,
    r_dest.distance_from_source AS dest_km,
    (r_dest.distance_from_source - r_src.distance_from_source) AS distance_km,
    cc.class_code,
    cc.class_name,
    cc.base_fare_multiplier,
    -- Dynamic Fare Calculation formula:
    ((r_dest.distance_from_source - r_src.distance_from_source) * cc.base_fare_multiplier) AS dynamic_estimated_fare
FROM bookings b
JOIN routes r_src ON b.train_no = r_src.train_no AND b.source_stn_code = r_src.stn_code
JOIN routes r_dest ON b.train_no = r_dest.train_no AND b.destination_stn_code = r_dest.stn_code
JOIN tickets t ON b.pnr_10 = t.pnr_10
LEFT JOIN train_composition tc ON t.composition_id = tc.composition_id
LEFT JOIN coach_classes cc ON tc.class_code = cc.class_code;

-- STEP 6: SEED POPULATION DATA (Static Metadata Setup)
INSERT INTO stations (stn_code, city, stn_name, state) VALUES ('NDLS', 'New Delhi', 'New Delhi Railway Station', 'Delhi');
INSERT INTO stations (stn_code, city, stn_name, state) VALUES ('KNP', 'Kanpur', 'Kanpur Central', 'Uttar Pradesh');
INSERT INTO stations (stn_code, city, stn_name, state) VALUES ('DDU', 'Pt. Deen Dayal Upadhyaya', 'Mughalsarai Junction', 'Uttar Pradesh');
INSERT INTO stations (stn_code, city, stn_name, state) VALUES ('HWH', 'Kolkata', 'Howrah Junction', 'West Bengal');

INSERT INTO trains (train_no, train_name, train_type, active_days) VALUES ('12302', 'Howrah Rajdhani Express', 'Rajdhani', '1111111');

-- Dynamic values converted to absolute minutes-since-midnight offsets
-- Departure 16:50 => 1010 min, Arrival 21:30 => 1290 min, etc.
INSERT INTO routes (train_no, stn_code, arrival_time, depart_time, sequence_num, distance_from_source) VALUES ('12302', 'NDLS', NULL, 1010, 1, 0);
INSERT INTO routes (train_no, stn_code, arrival_time, depart_time, sequence_num, distance_from_source) VALUES ('12302', 'KNP', 1290, 1295, 2, 448);
INSERT INTO routes (train_no, stn_code, arrival_time, depart_time, sequence_num, distance_from_source) VALUES ('12302', 'DDU', 45, 55, 3, 780);
INSERT INTO routes (train_no, stn_code, arrival_time, depart_time, sequence_num, distance_from_source) VALUES ('12302', 'HWH', 485, NULL, 4, 1450);

-- Static Coach Configuration Layout Catalog
INSERT INTO coach_classes (class_code, class_name, total_seats, base_fare_multiplier) VALUES ('1A', 'AC First Class', 24, 4.20);
INSERT INTO coach_classes (class_code, class_name, total_seats, base_fare_multiplier) VALUES ('2A', 'AC 2-Tier', 48, 2.50);
INSERT INTO coach_classes (class_code, class_name, total_seats, base_fare_multiplier) VALUES ('3A', 'AC 3-Tier', 72, 1.70);
INSERT INTO coach_classes (class_code, class_name, total_seats, base_fare_multiplier) VALUES ('SL', 'Sleeper Class', 80, 0.60);

-- Generate dynamic scheduler run dates for transactional schedules
INSERT INTO train_instances (train_no, run_date, status) VALUES ('12302', TO_DATE('2026-04-10', 'YYYY-MM-DD'), 'Scheduled');

-- Dynamically map operational coach runs to physical train schedules
INSERT INTO train_composition (train_no, run_date, coach_label, class_code) VALUES ('12302', TO_DATE('2026-04-10', 'YYYY-MM-DD'), 'B1', '3A');
INSERT INTO train_composition (train_no, run_date, coach_label, class_code) VALUES ('12302', TO_DATE('2026-04-10', 'YYYY-MM-DD'), 'B2', '3A');
INSERT INTO train_composition (train_no, run_date, coach_label, class_code) VALUES ('12302', TO_DATE('2026-04-10', 'YYYY-MM-DD'), 'H1', '1A');

-- STEP 7: SAFE TRANSACTION SEEDING ENGINE (PL/SQL)
DECLARE
    v_user_id NUMBER;
    v_comp_b1 NUMBER;
BEGIN
    -- 1. Create standard Passenger User (Bcrypt hashes require fixed 60-character lengths)
    INSERT INTO users (email, mobile, first_name, last_name, dob, gender, password_hash)
    VALUES ('traveler@example.com', '9876543210', 'Rahul', 'Sharma', TO_DATE('1992-05-15', 'YYYY-MM-DD'), 'Male', '$2b$12$hashedpasswordpaddedto60characterslongstringforbcryptxx')
    RETURNING user_id INTO v_user_id;

    -- 2. Fetch compositional operational reference
    SELECT composition_id INTO v_comp_b1 
    FROM train_composition 
    WHERE train_no = '12302' 
      AND run_date = TO_DATE('2026-04-10', 'YYYY-MM-DD') 
      AND coach_label = 'B1' 
      AND ROWNUM = 1;

    -- 3. Create Booking with clear stop-specific boundaries (NDLS to HWH)
    INSERT INTO bookings (pnr_10, user_id, train_no, journey_date, source_stn_code, destination_stn_code, quota, total_fare, status)
    VALUES ('4215567890', v_user_id, '12302', TO_DATE('2026-04-10', 'YYYY-MM-DD'), 'NDLS', 'HWH', 'GN', 2465.00, 'Booked');

    -- 4. Create Confirmed Ticket (linked to train composition instance)
    INSERT INTO tickets (pnr_10, passenger_name, passenger_age, passenger_gender, composition_id, seat_num, allocated_berth, status, wl_number)
    VALUES ('4215567890', 'Rahul Sharma', 34, 'Male', v_comp_b1, 14, 'LB', 'CNF', 0);

    -- 5. Create Waiting List Ticket
    INSERT INTO tickets (pnr_10, passenger_name, passenger_age, passenger_gender, composition_id, seat_num, allocated_berth, status, wl_number)
    VALUES ('4215567890', 'Aditi Rao', 28, 'Female', NULL, NULL, NULL, 'WL', 1);

    -- 6. Log dynamic Payment Record
    INSERT INTO payments (trans_id, pnr_10, amount, payment_status, payment_method)
    VALUES ('TXN_99887766', '4215567890', 2465.00, 'Success', 'UPI');

    -- 7. Register Master Profile
    INSERT INTO master_passengers (user_id, name, age, gender, preferred_berth)
    VALUES (v_user_id, 'Aditi Rao', 28, 'Female', 'UB');
END;
/

-- STEP 8: FLUSH & WRITE CHANGES PERMANENTLY
COMMIT;