-- ==========================================
-- RAILWAY RESERVATION SYSTEM - DATABASE SETUP
-- Target Engine: Oracle SQL*Plus (Docker XE)
-- ==========================================

-- STEP 1: DROP TABLES IN CORRECT SEQUENCE (Prevents Foreign Key Conflicts)
DROP TABLE master_passengers CASCADE CONSTRAINTS;
DROP TABLE payments CASCADE CONSTRAINTS;
DROP TABLE tickets CASCADE CONSTRAINTS;
DROP TABLE bookings CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE routes CASCADE CONSTRAINTS;
DROP TABLE coaches CASCADE CONSTRAINTS;
DROP TABLE trains CASCADE CONSTRAINTS;
DROP TABLE stations CASCADE CONSTRAINTS;

-- STEP 2: CREATE CORE INFRASTRUCTURE TABLES
CREATE TABLE stations (
    stn_code VARCHAR2(10) PRIMARY KEY,
    city VARCHAR2(106) NOT NULL,
    stn_name VARCHAR2(255) NOT NULL
);

CREATE TABLE trains (
    train_no VARCHAR2(10) PRIMARY KEY,
    train_name VARCHAR2(255) NOT NULL,
    train_type VARCHAR2(56) NOT NULL
);

CREATE TABLE coaches (
    coach_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_no VARCHAR2(10) REFERENCES trains(train_no) ON DELETE CASCADE,
    coach_label VARCHAR2(10) NOT NULL,
    class_type VARCHAR2(50) NOT NULL,
    total_seats INT NOT NULL
);

CREATE TABLE routes (
    route_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_no VARCHAR2(10) REFERENCES trains(train_no),
    stn_code VARCHAR2(10) REFERENCES stations(stn_code),
    arrival_time VARCHAR2(8), 
    depart_time VARCHAR2(8),
    sequence_num INT NOT NULL,
    distance_from_source INT DEFAULT 0,
    CONSTRAINT unique_train_stn UNIQUE(train_no, stn_code),
    CONSTRAINT unique_train_seq UNIQUE(train_no, sequence_num)
);

-- STEP 3: CREATE USER & TRANSACTION TABLES
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    mobile VARCHAR2(15) UNIQUE NOT NULL,
    first_name VARCHAR2(160) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    dob DATE NOT NULL,
    gender VARCHAR2(10) CHECK (gender IN ('Male', 'Female', 'Other')),
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'Passenger',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bookings (
    pnr_10 CHAR(10) PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    journey_date DATE NOT NULL,
    train_no VARCHAR2(10) REFERENCES trains(train_no),
    total_fare NUMBER(16, 2) NOT NULL,
    booking_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'Pending'
);

CREATE TABLE tickets (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnr_10 CHAR(10) REFERENCES bookings(pnr_10) ON DELETE CASCADE,
    passenger_name VARCHAR2(255) NOT NULL,
    passenger_age INT NOT NULL,
    coach_id INT REFERENCES coaches(coach_id),
    seat_num INT,
    status VARCHAR2(5) NOT NULL,
    wl_number INT DEFAULT 0
);

CREATE TABLE payments (
    trans_id VARCHAR2(180) PRIMARY KEY,
    pnr_10 CHAR(10) REFERENCES bookings(pnr_10),
    amount NUMBER(18, 2) NOT NULL,
    payment_status VARCHAR2(20) DEFAULT 'Success',
    payment_method VARCHAR2(50),
    paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE master_passengers (
    mstr_pass_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    name VARCHAR2(255) NOT NULL,
    age INT,
    gender VARCHAR2(10),
    preferred_berth VARCHAR2(20)
);

-- STEP 4: CREATE EFFICIENCY INDEXES
CREATE INDEX idx_route_station ON routes(stn_code, train_no);
CREATE INDEX idx_booking_date ON bookings(journey_date, train_no);
CREATE INDEX idx_booking_pnr ON bookings(pnr_10);

-- STEP 5: SEED POPULATION DATA
INSERT INTO stations (stn_code, city, stn_name) VALUES ('NDLS', 'New Delhi', 'New Delhi Railway Station');
INSERT INTO stations (stn_code, city, stn_name) VALUES ('KNP', 'Kanpur', 'Kanpur Central');
INSERT INTO stations (stn_code, city, stn_name) VALUES ('DDU', 'Pt. Deen Dayal Upadhyaya', 'Mughalsarai Junction');
INSERT INTO stations (stn_code, city, stn_name) VALUES ('HWH', 'Kolkata', 'Howrah Junction');

INSERT INTO trains (train_no, train_name, train_type) VALUES ('12302', 'Howrah Rajdhani Express', 'Express');

INSERT INTO coaches (train_no, coach_label, class_type, total_seats) VALUES ('12302', 'B1', 'AC 3-Tier', 72);
INSERT INTO coaches (train_no, coach_label, class_type, total_seats) VALUES ('12302', 'B2', 'AC 3-Tier', 72);
INSERT INTO coaches (train_no, coach_label, class_type, total_seats) VALUES ('12302', 'H1', 'AC 1st Class', 24);

INSERT INTO routes (train_no, stn_code, arrival_time, depart_time, sequence_num, distance_from_source) VALUES ('12302', 'NDLS', NULL, '16:50:00', 1, 0);
INSERT INTO routes (train_no, stn_code, arrival_time, depart_time, sequence_num, distance_from_source) VALUES ('12302', 'KNP', '21:30:00', '21:35:00', 2, 448);
INSERT INTO routes (train_no, stn_code, arrival_time, depart_time, sequence_num, distance_from_source) VALUES ('12302', 'DDU', '00:45:00', '00:55:00', 3, 780);
INSERT INTO routes (train_no, stn_code, arrival_time, depart_time, sequence_num, distance_from_source) VALUES ('12302', 'HWH', '08:05:00', NULL, 4, 1450);

INSERT INTO users (email, mobile, first_name, last_name, dob, gender, password_hash) VALUES ('traveler@example.com', '9876543210', 'Rahul', 'Sharma', TO_DATE('1992-05-15', 'YYYY-MM-DD'), 'Male', '$2b$12$hashedpassword');
INSERT INTO bookings (pnr_10, user_id, train_no, journey_date, total_fare, status) VALUES ('4215567890', 1, '12302', TO_DATE('2026-04-10', 'YYYY-MM-DD'), 2450.00, 'Confirmed');
INSERT INTO tickets (pnr_10, passenger_name, passenger_age, coach_id, seat_num, status, wl_number) VALUES ('4215567890', 'Rahul Sharma', 34, 1, 14, 'CNF', 0);
INSERT INTO payments (trans_id, pnr_10, amount, payment_method) VALUES ('TXN_99887766', '4215567890', 2450.00, 'UPI');
INSERT INTO tickets (pnr_10, passenger_name, passenger_age, coach_id, seat_num, status, wl_number) VALUES ('4215567890', 'Aditi Rao', 28, 1, NULL, 'WL', 1);

-- STEP 6: COMMIT TRANSACTION PERMANENTLY
COMMIT;